server:
  port: 9001

spring:
  profiles:
    active:
    - dev 
---
spring:
  profiles: dev     #开发环境
  application: 
    name: springconfig-dev
---
spring: 
  profiles: test    #测试环境
  application:
    name: springconfig-test  