spring:
  port: 9002
  application:
    name: config-client
  profiles: 
    active: 
      - dev
---


server:
  port: 8002

spring:
  datasource:
    username: root
    password: msroot     
    url: jdbc:mysql://39.107.44.147/demoDb?useUnicode=true&characterEncoding=UTF-8&useSSL=false
  profiles: dev
  application: 
    name: config-client-dev
  